name: actix-demo
services:
  - dockerfile_path: Dockerfile
    github:
      branch: master
      deploy_on_push: true
      repo: EvoTeamDevelop/actix-demo
    name: actix-demo
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
